name = "cloudflare-notepad"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "NOTES"
bucket_name = "cloud-notepad-notes"

[build]
command = "worker-build --release"

[assets]
directory = "static"
binding = "ASSETS"


[observability]
enabled = true
head_sampling_rate = 1
