name = "cloudflare-notepad"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "NOTES"
id = "b485b873ed1a41d686bb26799e2eb527"

[build]
command = "worker-build --release"

[assets]
directory = "static"
binding = "ASSETS"


[observability]
enabled = true
head_sampling_rate = 1
