import type { SupportedLanguageMap } from './types'

// server side salt kept for legacy password verification
export const LEGACY_SALT = SCN_SALT
// server side secret
export const SECRET = SCN_SECRET
// optional admin password used to protect .index editing
export const INDEX_EDIT_PASSWORD = typeof SCN_INDEX_PASSWD === 'string' ? SCN_INDEX_PASSWD : ''

// supported language
export const SUPPORTED_LANG: SupportedLanguageMap = {
    en: {
        setPW: 'Set Password',
        changePW: 'Change Password',
        share: 'Share',
        lastModified: 'Last modified',
        copy: 'Copy',
        emptyPH: 'There are many like it, but this one is mine...',
        tipEncrypt: 'This note is protected. Enter the password to continue.',
        tip404: '404, nothing here.',
        tipPrivate: 'This note is not publicly shared.',
        editButtonText: 'Edit',
        rawButtonText: 'Raw',
        err: 'Error',
        enterPasswordPrompt: 'Enter the note password',
        passwordSetPrompt: 'Set a password for this note. Leave empty to remove it.',
        passwordSaved: 'Password updated.',
        passwordRemoved: 'Password removed.',
        shareCopied: 'Share link copied.',
        authFailed: 'Password authentication failed.',
        formatNow: 'Format Now',
        formatMode: 'Format',
        formatApplied: 'Formatting applied.',
        formatFailed: 'Formatting failed.',
        mdViewEdit: 'Edit',
        mdViewSplit: 'Split',
        mdViewPreview: 'Preview',
        homeKicker: 'Cloud Notepad',
        homeTitle: 'A lightweight workspace for quick notes and secure sharing.',
        homeCopy: 'Keep the interface simple, create notes quickly, and use one focused editor when you need to write, preview, or share.',
        homeNewNote: 'New Note',
        homeEditHome: 'Edit Home',
        homeQuickStart: 'Quick Start',
        homeQuickStartCreate: 'Create a note from a random path.',
        homeQuickStartEdit: 'Edit in one merged writing surface.',
        homeQuickStartProtect: 'Protect the note when private reading matters.',
        homeEmptyNote: 'No content yet. Use "Edit Home" to add your own dashboard notes.',
    },
    zh: {
        setPW: '设置密码',
        changePW: '修改密码',
        share: '分享',
        lastModified: '上次保存',
        copy: '复制',
        emptyPH: '这里还没有内容，写点什么吧...',
        tipEncrypt: '这条笔记受密码保护，请先输入密码。',
        tip404: '404，你要找的内容不存在。',
        tipPrivate: '这条笔记未公开分享。',
        editButtonText: '编辑',
        rawButtonText: '原文',
        err: '错误',
        enterPasswordPrompt: '请输入笔记密码',
        passwordSetPrompt: '请设置笔记密码，留空即可移除密码。',
        passwordSaved: '密码已更新。',
        passwordRemoved: '密码已移除。',
        shareCopied: '分享链接已复制。',
        authFailed: '密码验证失败。',
        formatNow: '一键格式化',
        formatMode: '格式',
        formatApplied: '已应用格式化。',
        formatFailed: '格式化失败。',
        mdViewEdit: '编辑',
        mdViewSplit: '分栏',
        mdViewPreview: '预览',
        homeKicker: '云端便笺',
        homeTitle: '一个轻量的工作台，用于快速记录与安全分享。',
        homeCopy: '保持界面简洁，快速创建笔记，在同一个编辑器里完成编写、预览与分享。',
        homeNewNote: '新建笔记',
        homeEditHome: '编辑首页',
        homeQuickStart: '快速开始',
        homeQuickStartCreate: '通过随机路径快速创建一篇新笔记。',
        homeQuickStartEdit: '在统一的编辑界面中完成写作与预览。',
        homeQuickStartProtect: '需要私密阅读时，可以为笔记启用保护。',
        homeEmptyNote: '还没有首页内容，点击“编辑首页”添加你的仪表盘笔记。',
    },
}
